
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and modules
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: "Run pytest on ${{ matrix.os }} for ${{ matrix.python-version }}"
        run: |
          pip install pytest
          pytest tests
